### ISSUE TITLE
Fatal: ffmpeg non-functional

### ISSUE THREAD

**Issue by luhrMan** [outlyer-net/docker-losslesscut#7]
Hi, thank you for the work into this container.

I launched the compose file with `docker compose up -d` on a Raspberry pi (arm architecture) running Raspi OS Lite. When I connect to the server through Firefox, I receive this error:
![Screenshot from 2024-10-22 19-50-16](https://github.com/user-attachments/assets/2c399564-7a2b-4e95-962d-1bc6e8bd625e)

Here is my compose file:
``` bash
name: losslesscut

services:
  losslesscut:
    image: outlyernet/losslesscut
    build: .
    restart: unless-stopped
    ports:
      - 5800:5800/tcp
    volumes:
      # Configuration directory, beware of permissions
      - ./config:/config:rw
      # Video files will be looked for here
      - /mnt/nfs/Media/test:/storage:rw
      # Alternative path matching the host
      #- ${HOME}:${HOME}:rw
    environment:
      WEB_AUDIO: ${WEB_AUDIO:-1}
      DARK_MODE: ${DARK_MODE:-1}
      #SECURE_CONNECTION: ${SECURE_CONNECTION:-1}
```

Any help or advice would be appreciated

**Comment by outlyer-net** [comment]
You're right, LosslessCut's arm archives don't contain ffmpeg, I'll look into some way to solve it

**Comment by outlyer-net** [comment]
The updated container should do the trick, I haven't tested it thoroughly but it starts normally now and I was able to load videos and move on the timeline normally.
Let me know if there's some issue with it.

**Comment by luhrMan** [comment]
It works now, thank you so much. I had attempted to add an install of ffmpeg in the Dockerfile myself, but I am still quite a novice at this and could not get it to work.

I appreciate the quick solution.
